# Generated by Django 4.1.7 on 2023-02-22 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_userprofile_delete_customer_delete_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile", old_name="icon", new_name="user_info",
        ),
    ]
