# Generated by Django 4.1.7 on 2023-02-22 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_rename_icon_userprofile_user_info"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile", old_name="user_info", new_name="user",
        ),
    ]
