# Generated by Django 4.1.7 on 2023-02-22 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_rename_user_info_userprofile_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile", old_name="age", new_name="image",
        ),
    ]
