# Generated by Django 4.1.7 on 2023-03-02 09:01

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_alter_photo_post_alter_post_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=imagekit.models.fields.ProcessedImageField(
                null=True, upload_to="photos/%Y/%m/%d/"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="icon",
            field=imagekit.models.fields.ProcessedImageField(
                null=True, upload_to="icons/%Y/%m/"
            ),
        ),
    ]
