# Generated by Django 4.1.7 on 2023-03-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_alter_photo_image_alter_userprofile_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=models.ImageField(null=True, upload_to="photos/%Y/%m/"),
        ),
    ]
