# Generated by Django 4.1.7 on 2023-03-02 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_photo_updated_at_post_created_at_post_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(blank=True, to="myapp.userprofile"),
        ),
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(blank=True, to="myapp.tag"),
        ),
    ]
